### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by cmeeren** [adrianiftode/FluentAssertions.Web#117]
I am always wary of updating packages if I don't know what's changed. I suggest adding a changelog to this repo, that contains at least the changes in 1.2.5.

For a suggested changelog format, see [Keep a changelog](https://keepachangelog.com/en/1.0.0/). The most important part, however, is simply having a list of changes.

**Comment by adrianiftode** [comment]
Doesn't the releases tab help?

https://github.com/adrianiftode/FluentAssertions.Web/releases

**Comment by cmeeren** [comment]
Thanks! The link works for me, but it's neither in the tab list nor in the sidebar like I'm used to.

<img width="1569" alt="image" src="https://user-images.githubusercontent.com/7766733/214390948-8269fac4-97f5-4d18-9dbc-06b8849913ca.png">

**Comment by adrianiftode** [comment]
Ok, thanks, should be fine now, I had to configure it to be visible there.

![image](https://user-images.githubusercontent.com/13752939/214426102-672c09b6-ebd8-49d9-a374-1e1fb003c3ae.png)

**Comment by cmeeren** [comment]
Thanks! 👍
