### ISSUE TITLE
Consider migrating from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by adrianiftode** [adrianiftode/FluentAssertions.Web#50]
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0

**Comment by MattConroy** [comment]
This change seems to have introduced unexpected behaviour.
It looks like .HaveError(...) does not correctly pick up errors from the response now.
Rolling back to v1.1.1 fixes the problem.

The output from the test is as follows:
`Expected response to contain the error message "Cannot add at Revoked Status." related to the "Status" field, but no such message was found in the actual error messages list: 

The HTTP response was:

HTTP/1.1 400 BadRequest
Content-Type: application/json; charset=utf-8
Content-Length: 263

{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-deb7480af23a884e942f7b85cac6bd35-c1abe72874d40c4a-00",
  "errors": {
    "Status": [
      "Cannot add at Revoked Status."
    ]
  }
}`

**Comment by adrianiftode** [comment]
Hi, Matt, thanks for reporting.

This has been fixed in 1.1.7

I will try in the future to add back Newtonsoft.Json, but under a feature
flag and it won't be the default deserializer.

Adrian
