### ISSUE TITLE
Incompatibility with FluentAssertions 6.0.0

### ISSUE THREAD

**Issue by hugoqribeiro** [adrianiftode/FluentAssertions.Web#63]
Hi.

The current version of the package does not work with FluentAssertions 6.0.0, recently released.

`Be401Unauthorized()`, for example, raised `MissingMethodException`.

**Comment by Numpsy** [comment]
Same thing here, the new packages installed ok, but when running the tests I get some errors like

```
  Error Message:
   System.MissingMethodException : Method not found: 'Void FluentAssertions.Primitives.ReferenceTypeAssertions`2..ctor()'.
  Stack Trace:
     at FluentAssertions.Web.HttpResponseMessageAssertions..ctor(HttpResponseMessage value)
   at FluentAssertions.HttpResponseMessageFluentAssertionsExtensions.Should(HttpResponseMessage actual)

```

Looks like ```ReferenceTypeAssertions``` in the FluentAssertions lib no longer has a parameterless constructor:

![image](https://user-images.githubusercontent.com/1178570/129701897-017f1b3f-3dc2-4ac5-bb1a-d097a6cf3808.png)

**Comment by adrianiftode** [comment]
I will take a look. I didn't test yet FA 6.0.0, hopefully, there are not too many breaking changes.
